
# Trigger pipeline on any branch push
trigger:
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x' # Replace with the version of .NET SDK you're using
     

    - script: dotnet build --configuration Release
      displayName: 'Build the project'

- stage: UnitTests
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: 'Unit Tests'
    steps:
    - script: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
      displayName: 'Run Unit Tests'

- stage: CodeReview
  dependsOn: UnitTests
  jobs:
  - job: PRJob
    displayName: 'Code Review'
    steps:
    - script: |
        echo "Create a Pull Request for Code Review"
        echo "Notify Scrum Master and Product Owner for approval"
      displayName: 'Create Pull Request and Notify Approvers'

   