# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'


variables:
  buildConfiguration: 'Dev'
  releaseBranchName: 'dev'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm 

  variables:
    wwwrootDir: 'frontend_mothership/wwwroot'
    dotnetSdkVersion: '1.0'
    
 