trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH_TOKEN: $(SNYK_AUTH_TOKEN) # Set this variable in your pipeline settings

stages:
- stage: BuildAndScan
  displayName: 'Build and Security Scan'
  jobs:
  - job: Build
    displayName: 'Build the project'
    pool:
       vmImage: 'ubuntu-20.04'
       steps:
       - task: NodeTool@0
         inputs:
         versionSpec: '14.x'  # Node version
         displayName: 'Install Node.js'
       - script: npm install
         displayName: 'Install Dependencies'
       - script: npm build
         displayName: 'Build Application'
       - script: npm test
         displayName: 'Run Unit Tests'
  
  - job: 'SnykScan'
    displayName: SnykScan
    dependsOn: Build
    condition: succeeded()
    pool:
     vmImage: ubuntu-latest
     steps:
      - task:
          inputs: 
            serviceConnectionEndpoint: ''
            testType: 'app'
            severityThreshold: 'medium'
            monitorWhen: 'always'
            failOnIssues: true
            projectName: 'frontend_mothership'
            organization: 'kgf'
     
      