trigger:
  branches:
    include:
      - features/*

pr:
  branches:
    include:
      - features/*
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH: '45678901'
  SNYK_AUTH_TOKEN: $(SNYK_AUTH) # Securely store this in Azure DevOps pipeline variables

jobs:
- job: BuildAndScan
  displayName: 'Build and Security Scan'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x' # Specify the Node.js version
      checkLatest: true
  

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm i sharp
    displayName: 'install image optimizer'

  - script: |
         npm install set fund false
         set cache .npm
  
  - script: npm run build
    displayName: 'Build the Project'
  - script: |
         npm install set fund false
         set cache .npm

  - script: |
      echo "Running Snyk security scan"
      npm install -g snyk set fund false
      
      snyk test --severity-threshold=high --json > snyk-results.json
    displayName: 'Run Snyk Scan'
 

  
