trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
pool:
  vmImage: 'ubuntu-latest'
variables:
  SNYK_AUTH: '45678901'
  SNYK_TOKEN: 'da364a31-6b96-412a-b516-c4d2bf4bc8fe'
  variables:
  rbuildConfiguration: 'Release'
  pBuildConfiguration: '--prod'

stages:
# Stage 1: Build & UnitTest
- stage: BuildAndTest
  displayName: 'Build & UnitTest & SnykScan'
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x' # Specify the Node.js version
        checkLatest: true
      displayName: 'Install Dependencies'
    - script: npm i sharp
      displayName: 'install image optimizer'
    - script: |
        npm config set fund false --location=global
        set cache .npm
        npm audit fix 
    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: '.'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install --legacy-peer-deps'
        workingDir: '.'
      displayName: 'npm install with custom'
        
    - task : Npm@1
      displayName: 'npm run build'
      inputs:
        command: 'custom'
        workingDir: '.'
        customCommand : 'run build'
  
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: |
            src/*
            public/*
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy project files'

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'        
    
 # Step 2 integrate security scans into the CI/CD pipeline.
  - job:
    pool:
      vmImage: ubuntu-latest
  - job: SnykScan
    displayName: 'SnykScan'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        npm config set fund false --location=global
        echo "Running Snyk security scan"
        npm install -g snyk 
      displayName: 'Run Snyk Scan'
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      workingDirectory: $(System.DefaultWorkingDirectory)
 
# Step 3: Approval to proceed to the testing environment
- stage: TestDeployment
  displayName: 'Test Environment Deployment'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - deployment: DeployToTest
    displayName: 'Deploy to Test Environment'
    environment: 'Test' # Define the environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Test Environment"
              # Deployment script or command (e.g., Azure CLI, Kubernetes, etc.)
              # Example for a Node.js app deployment:
              # az webapp deployment source config-zip --resource-group <resource-group> --name <app-name> --src <path-to-zip>
            displayName: 'Deploy Application'
            
          - script: |
              echo "Running Integration Tests"
              
            displayName: 'Run Integration Tests'

          - script: |
              echo "Running System Tests"
              
            displayName: 'Run System Tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/test-results/*.xml'
              testResultsFormat: 'JUnit'
              failTaskOnFailedTests: true
            displayName: 'Publish Test Results'

             # Add deployment scripts/commands here (e.g., ARM templates, Kubernetes manifests)
                   
- stage: Staging
  displayName: 'Deploy to Staging'
  dependsOn: BuildAndTest
  jobs:
  - deployment: DeployToStaging
    displayName: 'Deploy to Staging'
    environment: 'staging'
    pool:
     vmImage: 'ubuntu-latest'
    strategy:
          runOnce:
            deploy:
              steps:
              - script: |
                   templates/npm-steps.yml
                    echo "Conduct UAT..."
                    # Replace with actual UAT commands if any
                displayName: 'Conduct UAT'
 - script: |
        npm install -g snyk
        snyk auth $(SNYK_TOKEN)
         snyk test
      displayName: 'Run Snyk Security Scan'
      env:
         SNYK_TOKEN: $(SNYK_TOKEN)

          # Step 3: Analyze Snyk scan results
    - task: Bash@3
      displayName: 'Check Snyk Results'
      inputs:
         targetType: 'inline'
         script: |
            snyk test --json > snyk-report.json
            if grep -q '"vulnerabilities": \[\]' snyk-report.json; then
             echo "No vulnerabilities found."
              else
                  echo "Critical vulnerabilities found. Failing build."
                  exit 1
                fi            
  
- stage: Production
  displayName: 'Deploy to Production'
  dependsOn: SecurityScan
  condition: succeeded()
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy to Production'
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
        deploy:
          steps: 
          - script: |
              echo "Deploying to Production..."
              # Replace with actual deployment script using CPanel
            displayName: 'Deploy to Production'
          - task: SendEmail@1
            inputs:
              to: 'awogao@gmail.com'
              subject: 'Production Deployment Status'
              body: 'Deployment to production was successful!'
            displayName: 'Send Success Notification'