
# Trigger pipeline on any branch push
trigger:
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

  branches:
    include:
      - develop
variables: 
  dotnetSdkVersion: '6.x'
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  
 # Build Stage
stages:
  - stage: 'Build'
    displayName: 'Build Stage'
    jobs: 
    - job: 'build'
      displayName: 'Build job'
      pool:
       vmImage: 'ubuntu-20.04'
      steps:
      - task: NodeTool@0
        inputs:
         versionSpec: '14.x'  # Node version
        displayName: 'Install Node.js'
      - script: npm install
        displayName: 'Install Dependencies'

      - script: npm build
        displayName: 'Build Application'
      

  - stage: UnitTests
    dependsOn: Build
    jobs:
    - job: TestJob
      displayName: 'Unit Tests'
      steps:
       - script: npm run test --watch=false --loglevel verbose --single
         displayName: 'Run Unit Tests'

  - stage: CodeReview
    dependsOn: UnitTests
    jobs:
    - job: PRJob
      displayName: 'Code Review'
      steps:
      - script: |
           echo "Create a Pull Request for Code Review"
           echo "Notify Scrum Master and Product Owner for approval"
           displayName: 'Create Pull Request and Notify Approvers'

   