trigger:
  branches:
    include:
      - features/*

pr:
  branches:
    include:
      - features/*
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH: '45678901'
  SNYK_AUTH_TOKEN: $(SNYK_AUTH) # Securely store this in Azure DevOps pipeline variables

jobs:
- job: BuildAndScan
  displayName: 'Build and Security Scan'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x' # Specify the Node.js version
      checkLatest: true

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm i sharp
    displayName: 'install image optimizer'

  - script: |
         npm install set fund false
         set cache .npm
  
  - script: npm run build
    displayName: 'Build the Project'
  - script: |
         npm install set fund false
         set cache .npm

  - script: |
      echo "Running Snyk security scan"
      npm install -g snyk
      snyk auth $SNYK_AUTH_TOKEN
      snyk test --severity-threshold=high --json > snyk-results.json
    displayName: 'Run Snyk Scan'

  - script: |
      echo "Checking for Critical Vulnerabilities"
      cat snyk-results.json
      severityCount=$(jq '.vulnerabilities | map(select(.severity=="high" or .severity=="critical")) | length' snyk-results.json)
      if [ "$severityCount" -gt 0 ]; then
        echo "Critical vulnerabilities found!"
        return 0
      fi
    displayName: 'Check for Critical Vulnerabilities'

