trigger:
  branches:
    include:
      - develop

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: 'Build and Scan'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # Step 1: Check out the code from the repository
          - task: Checkout@1
            displayName: 'Checkout Code'
            inputs:
              clean: true

          # Step 2: Run Snyk security scan
          - script: |
              npm install -g snyk
              snyk auth $(SNYK_TOKEN)
              snyk test
            displayName: 'Run Snyk Security Scan'
            env:
              SNYK_TOKEN: $(SNYK_TOKEN)

          # Step 3: Analyze Snyk scan results
          - task: Bash@3
            displayName: 'Check Snyk Results'
            inputs:
              targetType: 'inline'
              script: |
                snyk test --json > snyk-report.json
                if grep -q '"vulnerabilities": \[\]' snyk-report.json; then
                  echo "No vulnerabilities found."
                else
                  echo "Critical vulnerabilities found. Failing build."
                  exit 1
                fi

          # Step 4: Notify Scrum Master/Product Owner
          - task: SendEmail@1
            displayName: 'Notify Stakeholders'
            inputs:
              To: 'scrum.master@example.com;product.owner@example.com'
              Subject: 'Snyk Security Scan Results for $(Build.BuildId)'
              Body: |
                The Snyk security scan has been completed for build $(Build.BuildId).
                Please review the attached report for details.

  - stage: Approvals
    dependsOn: Build
    jobs:
      - job: ApprovalJob
        displayName: 'Approval Process'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Step 5: Approval to proceed to the testing environment
          - task: ManualValidation@0
            displayName: 'Approval to Proceed to Testing'
            inputs:
              instructions: 'Review the Snyk scan results and approve to proceed if there are no critical vulnerabilities.'
              approvers: |
                - scrum.master@example.com
                - product.owner@example.com
