trigger:
  branches:
    include:
      - features/*

pr:
  branches:
    include:
      - features/*
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH: '45678901'
  SNYK_AUTH_TOKEN: $(SNYK_AUTH) # Securely store this in Azure DevOps pipeline variables

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x' # Specify the Node.js version
      checkLatest: true
  - script: npm install
    displayName: 'Install Dependencies'
  - script: npm i sharp
    displayName: 'install image optimizer'
  - script: |
         npm install set fund false
         set cache .npm

  - script: npm run build
    displayName: 'Build Application'
  
  - script: |
       npm uninstall -g create-react-app
       npm rm -g create-react-app
       npm install -g create-react-app
       npx create-react-app my-app
       npm run test --watch=false --loglevel verbose --single
    displayName: 'Run Unit Tests'

- job: SnykScan
  displayName: 'Snyk Security Scan'
  dependsOn: 'Build'
  steps:
  - script: |
        echo "Running Snyk security scan"
        npm install -g snyk 
        npm config set fund false
        
    displayName: 'Run Snyk Scan'

         


  