trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH: '45678901'
  SNYK_AUTH_TOKEN: $(SNYK_AUTH) # Securely store this in Azure DevOps pipeline variables

stages:
# Stage 1: Build and Test
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x' # Specify the Node.js version
        checkLatest: true
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Install Dependencies'
    - script: npm i sharp
      displayName: 'install image optimizer'
    - script: |
        npm install set fund false
        set cache .npm
        npm audit fix set fund false
        npm ci test 
      displayName: 'Run Unit Tests'
  - job: SnykScan
    displayName: 'SnykScan'
    dependsOn: 'BuildAndTest'
    condition: succeeded() # Only proceed if the Build and Test stage is successful
    pool:
      vmImage: ubuntu-latest
    steps:
     - script: |
        echo "Running Snyk security scan"
        npm install -g snyk 
        npm config set fund false
       displayName: 'Run Snyk Scan'