trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
pool:
  vmImage: 'ubuntu-latest'
variables:
  SNYK_AUTH: '45678901'
  SNYK_AUTH_TOKEN: $(SNYK_AUTH) # Securely store this in Azure DevOps pipeline variables
  variables:
  rbuildConfiguration: 'Release'
  pBuildConfiguration: '--prod'

stages:
# Stage 1: Build & UnitTest
- stage: BuildAndTest
  displayName: 'Build & UnitTest & SnykScan'
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x' # Specify the Node.js version
        checkLatest: true
      displayName: 'Install Dependencies'

    - script: |
        npm audit fix --force
        npm i sharp 
        npm config set fund false --location=global
        set cache .npm
        npm install
      displayName: 'Install Node.js'
      workingDirectory: $(System.DefaultWorkingDirectory)/
      
    - script: |
       npm audit fix --force
       npm ci test
      displayName: 'Run Unit Tests'
      workingDirectory: $(System.DefaultWorkingDirectory)/
    
    - script: |
        
      displayName:  'publish apps'
      workingDirectory: $(System.DefaultWorkingDirectory)/
    
    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  
   
   
    
 
 # Step 2 integrate security scans into the CI/CD pipeline.
  - job:
    pool:
      vmImage: ubuntu-latest
  - job: SnykScan
    displayName: 'SnykScan'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        npm config set fund false --location=global
        echo "Running Snyk security scan"
        npm install -g snyk 
      displayName: 'Run Snyk Scan'
      workingDirectory: $(System.DefaultWorkingDirectory)/
    
   
# Step 3: Approval to proceed to the testing environment
- stage: TestDeployment
  displayName: 'Test Environment Deployment'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - deployment: DeployToTest
    displayName: 'Deploy to Test Environment'
    environment: 'Test' # Define the environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Test Environment"
              
            displayName: 'Deploy Application'     
          - script: |
              echo "Running Integration Tests"
              # Command to run integration tests
            displayName: 'Run Integration Tests'
          - script: |
              echo "Running System Tests"
              # Command to run system tests
            displayName: 'Run System Tests'

          - script: |
              echo "Generating Test Results"
              # Generate and publish test reports (use tasks like PublishTestResults@2)
    
- stage: Staging
  displayName: 'Deploy to Staging'
  dependsOn: BuildAndTest
  jobs:
  - deployment: DeployToStaging
    displayName: 'Deploy to Staging'
    environment: 'staging'
    pool:
     vmImage: 'ubuntu-latest'
    strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: Download artifacts
                inputs:
                  buildType: current
                  downloadPath: single
                  artifactName:  drop
                  downloadType: single
                  checkDownloadedFiles: true
            
              - script: |
                   templates/npm-steps.yml
                    echo "Conduct UAT..."
                    # Replace with actual UAT commands if any
                displayName: 'Conduct UAT'
              

- stage: SecurityScan
  displayName: 'Final Security Scanning'
  dependsOn: Staging
  condition: succeeded()
  jobs:
  - job: SnykScan
    displayName: 'Run Snyk Scan'
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - script: |
        npm config set fund false --location=global
        echo "Running Snyk security scan"
        npm install -g snyk 
      displayName: 'Run Snyk Scan'
  
- stage: Production
  displayName: 'Deploy to Production'
  dependsOn: SecurityScan
  condition: succeeded()
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy to Production'
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
        deploy:
          steps: 
          - script: |
              echo "Deploying to Production..."
              # Replace with actual deployment script using CPanel
            displayName: 'Deploy to Production'
          - task: SendEmail@1
            inputs:
              to: 'awogao@gmail.com'
              subject: 'Production Deployment Status'
              body: 'Deployment to production was successful!'
            displayName: 'Send Success Notification'