# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Dev'
  releaseBranchName: 'dev'
  dotnetSdkVersion: '6.x'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # specify the .NET version you're using

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build solution'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Run unit tests'

- task: CopyFiles@2
  inputs:
    contents: '**/bin/Release/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


