trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  SNYK_AUTH_TOKEN: $(SNYK_AUTH_TOKEN) # Set this variable in your pipeline settings

stages:
- stage: BuildAndScan
  displayName: 'Build and Security Scan'
  jobs:
  - job: Build
    displayName: 'Build the project'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x' # Replace with the appropriate .NET SDK version
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet build --configuration Release
      displayName: 'Build the project'

  - job: SnykScan
    displayName: 'Snyk Security Scan'
    dependsOn: Build
    steps:
    - script: |
        echo "Running Snyk security scan"
        snyk auth $SNYK_AUTH_TOKEN
        snyk test --severity-threshold=high --json > snyk-results.json
      displayName: 'Run Snyk Scan'

    - script: |
        cat snyk-results.json
        severityCount=$(jq '.vulnerabilities | map(select(.severity=="high" or .severity=="critical")) | length' snyk-results.json)
        if [ "$severityCount" -gt 0 ]; then
          echo "Critical vulnerabilities found!"
          exit 1
        fi
      displayName: 'Check for Critical Vulnerabilities'

- stage: NotifyAndApproval
  displayName: 'Notify and Approval'
  dependsOn: BuildAndScan
  condition: succeeded()
  jobs:
  - job: Notify
    displayName: 'Notify Scrum Master/Product Owner'
   
  - job: Approval
    displayName: 'Approval to Proceed'
    dependsOn: Notify
    steps:
    - script: |
        echo "Approval required to proceed to testing environment."
        # Implement the approval step here (e.g., manual intervention, gate approval)
      displayName: 'Manual Approval Step'
