trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'



stages:
- stage: BuildAndScan
  displayName: 'Build and Security Scan'
  jobs:
  - job: Build
    displayName: 'Build the project'
    pool:
       vmImage: 'ubuntu-20.04'
       steps:
       - task: NodeTool@0
         inputs:
         versionSpec: '14.x'  # Node version
         displayName: 'Install Node.js'
       - script: npm install
         displayName: 'Install Dependencies'
       - script: npm build
         displayName: 'Build Application'
       - script: npm test
         displayName: 'Run Unit Tests'
  
  - job: 'SnykScan'
    displayName: SnykScan
    dependsOn: Build
    condition: succeeded()
    pool:
     vmImage: ubuntu-latest
     steps:
      - task:
          inputs: 
            serviceConnectionEndpoint: ''
            testType: 'app'
            severityThreshold: 'medium'
            monitorWhen: 'always'
            failOnIssues: true
            projectName: 'frontend_mothership'
            organization: 'kgf'
     
- stage: NotifyAndApproval
  displayName: 'Notify and Approval'
  dependsOn: BuildAndScan
  condition: succeeded()
  jobs:
   - job: Notify
     displayName: 'Notify Scrum Master/Product Owner'
   
   - job: Approval
     displayName: 'Approval to Proceed'
     dependsOn: Notify
     steps:
     - script: |
        echo "Approval required to proceed to testing environment."
        # Implement the approval step here (e.g., manual intervention, gate approval)
       displayName: 'Manual Approval Step'